- name: Install python-minimal on hosts
  hosts: vpnservers
  gather_facts: False
  remote_user: root
  tasks:
    - name: install python first
      raw: apt-get install -y python-minimal python-pip
      ignore_errors: True


- name: Configuring Base system (updates, swap, sysctl)
  hosts: vpnservers
  become: true
  gather_facts: True

  roles:
    - common
    - swap
    - sysctl
    - unattended-upgrades

- name: Installing dropbear
  hosts: vpnservers
  become: true

  roles:
    - dropbear

- name: Installing DHCP Server
  hosts: vpnservers
  become: true

  roles:
    - isc-dhcp-server

- name: Installing DNS server
  hosts: vpnservers
  become: true

  roles:
    - bind9

- name: Installing HAProxy
  hosts: vpnservers
  become: true

  roles:
    - haproxy

- name: Installing UDP-Gateway
  hosts: vpnservers
  become: true

  roles:
    - badvpn-udpgw


- name: Installing SoftEtherVPN from git
  hosts: vpnservers
  become: true

  roles:
    - bridge
    - softethervpn
