---
# task file for configuring sysctl

- name: change vm.swappiness to 10
  sysctl:
    name: vm.swappiness
    value: 10
    sysctl_set: yes
    state: present
    reload: yes

- name: change vm.vfs_cache_pressure to 50
  sysctl:
    name: vm.vfs_cache_pressure
    value: 50
    sysctl_set: yes
    state: present
    reload: yes

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
