---
# task file for creating bridge interface

- name: make sure the bridge-utils package is present
  package:
    name: bridge-utils
    state: present

- name: gather os specific variables
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
