---
# OS Specific Tasks:  Ubuntu 17.10

- set_fact:
    netplan_bridge: "{{ lookup('template', 'templates/netplan_bridges.yaml.j2') }}"

- name: add bridges to netplan
  blockinfile:
    dest: /etc/netplan/99-bridges.yaml
    content: '{{ netplan_bridges }}'
    state: present

- name: apply netplan
  shell: netplan apply
